### ISSUE TITLE
Email campaign is a terrible idea

### ISSUE THREAD

**Issue by MicroPanda123** [Lenny4/DeepFaceLabClient#69]
I know you want to make people aware of that project, but sending emails to random people (I assume it's random, I have no idea why I got that email) is just bad strategy, especially when AI is hot topic currently, so it's really easy ground for scammers, which makes emails like yours seem fishy.

Project seems interesting, but I still went on and searched for that project by hand, because no way I would click any link in that email.

Best regards.

**Comment by Lenny4** [comment]
Hi @MicroPanda123 @Riteo and all people who didn't want to received this email,

It seems like I was a bit too optimistic. As you said it was good intent.

But it seems like I bother a lot of people with that email.

To say it clearly: I'm sorry. It won't happen again for this project or any other project which I might create in the future.

### For those who are wondering how I got your email

I didn't send to "random" people, in fact I used the [Github API](https://docs.github.com/en/rest/overview/about-githubs-apis?apiVersion=2022-11-28).

- First I made a call on [List stargazer](https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#list-stargazers), which allowed me to get users who starred the [DeepFaceLab repo](https://github.com/iperov/DeepFaceLab)
- Then I was able to get the email of the user either with the [Get a user](https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-a-user) api or [List public events for a user](https://docs.github.com/en/rest/activity/events?apiVersion=2022-11-28#list-public-events-for-a-user) api

If you have never been interested in DeepFake, I don't know how, but at some point the github API returns your email during one of this call.

I will keep this issue open for a few days so that everyone who wishes for can complain.

It was a bad idea, it won't happen again.

**Comment by ni554n** [comment]
I purposefully avoid starring any deepfake repo but the got the email 🤷

**Comment by mkp-rh** [comment]
> users who starred the

This account has never starred any repo's, you may have sent those emails out to a wider audience than intended.

**Comment by rainyskye** [comment]
Yeah, I've never actually interacted or even ever opened the DeepFaceLab repo or anything similar.

Kind of annoying to receive a random email. Most likely would also push some people away from your project.

**Comment by MicroPanda123** [comment]
@Lenny4 
> It was a bad idea, it won't happen again.
Yeah, it kinda was. But no worries, it is slight annoyance and we know u meant well.
It's important to learn from mistakes haha

**Comment by MicroPanda123** [comment]
It was kinda good exercise on basic Internet Safety tho lol

**Comment by PassiveLemon** [comment]
I was confused as to how I was emailed for this when I have never even seen this repository, let alone star it. I've looked at it a bit and it seems fairly interesting though so I'm not too upset

**Comment by userbradley** [comment]
I never consented for you to use my email for marketing. I have reported you to the ICO.

This is in breach of GDPR.

Stop this immediately.

**Comment by userbradley** [comment]
I have reported this GitHub repository to GitHub for spam and forwarded them all emails I have received.

That was not cool. You emailed ALL my email address. EVEN MY WORK ONE?! And I've never even looked at this repository

This is seriously not cool. And in breach of GDPR like I mentioned.

**Comment by Lenny4** [comment]
Here is the source code used to get the emails:

https://github.com/Lenny4/find-stargazers-emails

Please notice that if you want your email adress to be private on github go to:

https://github.com/settings/emails

And check `Keep my email addresses private`

**Comment by ngoclong19** [comment]
> And check `Keep my email addresses private`

> If you want command line Git operations to use your private email you must [set your email in Git](https://docs.github.com/articles/setting-your-email-in-git).

Email address could still be exposed via public commit, so the second step needs to be configure.

**Comment by rainyskye** [comment]
Some people still want to have their email public lol, it's not about hiding it it's about not misusing and mis-sending emails to people, I never interacted with the deepfake repos yet still got an email, as referenced in: https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#7-information-usage-restrictions

```
You may not use information from the Service (whether scraped, collected through our API, or obtained otherwise) for spamming purposes, including for the purposes of sending unsolicited emails to users or selling personal information, such as to recruiters, headhunters, and job boards.
```
> sending unsolicited emails

**Comment by Rage997** [comment]
You sent an email to my work email, which, does not have a github account. It just does not add up with what you said about how you got our emails. I also would like to remark that my github account (the one I am typing from now) has never starred this repo or any of your repos. Why lie about how you got our emails for marketing if not for malicious reasons?

**Comment by ngoclong19** [comment]
Dear @Rage997, I'm thinking you have a slight mistake.

You have starred the DeepFaceLab repo:
`https://github.com/Rage997?q=deepface&tab=stars&type=&sort=&direction=`

And if `****@mnd**.com` is your work email, it is available here:
`https://api.github.com/users/Rage997/events/public`

I know you are upset, but I think we should calm down instead of accusing other lying.
The repo's owner acknowledge that they did a bad thing, and someone has already report this incident to GitHub.

Why not take time to make sure that we didn't *accidentally* leak out confidential information, by following what they did to collect our email?
We cannot stop malicious actor from collecting our data, so I think we should do our best to protect it.

**Comment by mkp-rh** [comment]
I think there might be some bug in this API in github. When I check my own list of starred repositories:

> https://api.github.com/users/mkp-rh/starred

I get an empty list.

But when I search for stars in my profile:

> https://github.com/mkp-rh?q=Deep&tab=stars&type=&sort=&direction=

I'm met with thousands of starred projects.

**Comment by Rage997** [comment]
@Lenny4 and @ngoclong19 thank you both for clarifying. I apologize for my tone. I was just extremely annoyed about receiving an email on my work email. It's weird that it is linked (and available) to my personal GitHub profile. Thanks for showing it to me. I shall now look into how to remove it
